# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.4.0+mc26.1
maven_group=net.yak.bundled
archives_base_name=bundled

# Dependencies
fabric_api_version=0.149.0+26.1.2